import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppStore } from '../store/useAppStore';
import { SECTORS } from '../data/mockData';
import { DashboardLayout } from '../layouts/DashboardLayout';
import { Card, CardContent } from '../components/Card';
import { Button } from '../components/Button';
import {
  ChevronDown, ChevronUp, FileText, CheckCircle2, Clock, AlertCircle,
  BookOpen, ArrowRight, Upload, Shield
} from 'lucide-react';
import './Checklist.css';

const STATUS_CONFIG = {
  'not-started': { label: 'Not Started', color: '#94a3b8', bg: '#f1f5f9', icon: Clock },
  'in-progress': { label: 'In Progress', color: '#f59e0b', bg: '#fefce8', icon: AlertCircle },
  'approved': { label: 'Approved', color: '#10b981', bg: '#ecfdf5', icon: CheckCircle2 },
  'rejected': { label: 'Rejected', color: '#ef4444', bg: '#fef2f2', icon: AlertCircle },
};

export function Checklist() {
  const navigate = useNavigate();
  const checklist = useAppStore((state) => state.generatedChecklist);
  const formData = useAppStore((state) => state.businessFormData);
  const updateChecklistItemStatus = useAppStore((state) => state.updateChecklistItemStatus);
  const [expandedId, setExpandedId] = useState(null);

  const sectorLabel = SECTORS.find(s => s.value === formData.sector)?.label || 'Your Sector';

  const totalItems = checklist.length;
  const approved = checklist.filter(i => i.status === 'approved').length;
  const inProgress = checklist.filter(i => i.status === 'in-progress').length;
  const progressPercent = totalItems > 0 ? Math.round(((approved + inProgress * 0.5) / totalItems) * 100) : 0;

  if (checklist.length === 0) {
    return (
      <DashboardLayout>
        <div className="checklist-empty">
          <Shield size={48} />
          <h2>No Checklist Generated</h2>
          <p>Please fill in your business profile first to generate an approval checklist.</p>
          <Button variant="primary" onClick={() => navigate('/onboarding')}>
            Go to Business Profile <ArrowRight size={16} style={{ marginLeft: '8px' }} />
          </Button>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="checklist-page">
        {/* Header */}
        <div className="checklist-header">
          <div>
            <h1 className="checklist-title">Your Compliance Checklist</h1>
            <p className="checklist-subtitle">
              {totalItems} approvals identified for <strong>{sectorLabel}</strong> — generated by the UdyamOne Rules Engine
            </p>
          </div>
          <Button variant="primary" onClick={() => navigate('/upload-documents')}>
            <Upload size={16} style={{ marginRight: '8px' }} /> Upload Documents
          </Button>
        </div>

        {/* Progress Bar */}
        <Card className="checklist-progress-card">
          <CardContent style={{ padding: '20px 24px' }}>
            <div className="progress-header">
              <span className="progress-label">Overall Progress</span>
              <span className="progress-value">{progressPercent}%</span>
            </div>
            <div className="progress-bar-track">
              <div className="progress-bar-fill" style={{ width: `${progressPercent}%` }}></div>
            </div>
            <div className="progress-stats">
              <span><CheckCircle2 size={14} /> {approved} Approved</span>
              <span><Clock size={14} /> {inProgress} In Progress</span>
              <span><AlertCircle size={14} /> {totalItems - approved - inProgress} Pending</span>
            </div>
          </CardContent>
        </Card>

        {/* Checklist Items */}
        <div className="checklist-items">
          {checklist.map((item, index) => {
            const isExpanded = expandedId === item.id;
            const statusConf = STATUS_CONFIG[item.status];
            const StatusIcon = statusConf.icon;

            return (
              <Card key={item.id} className={`checklist-item-card ${isExpanded ? 'expanded' : ''}`}>
                <button
                  className="checklist-item-header"
                  onClick={() => setExpandedId(isExpanded ? null : item.id)}
                >
                  <div className="ci-left">
                    <span className="ci-number">{index + 1}</span>
                    <div className="ci-info">
                      <h3>{item.name}</h3>
                      <span className="ci-dept">{item.department}</span>
                    </div>
                  </div>
                  <div className="ci-right">
                    <span className="ci-sla">SLA: {item.sladays} days</span>
                    <span
                      className="ci-status-badge"
                      style={{ color: statusConf.color, background: statusConf.bg }}
                    >
                      <StatusIcon size={14} /> {statusConf.label}
                    </span>
                    {isExpanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                  </div>
                </button>

                {isExpanded && (
                  <div className="checklist-item-body">
                    {/* RAG Explanation */}
                    <div className="ci-explanation">
                      <BookOpen size={16} />
                      <p>{item.explanation}</p>
                    </div>

                    {/* Citation */}
                    <div className="ci-citation">
                      <FileText size={14} />
                      <span>{item.citation}</span>
                    </div>

                    {/* Required Documents */}
                    <div className="ci-documents">
                      <h4>Required Documents</h4>
                      <ul>
                        {item.documents.map((doc, i) => (
                          <li key={i}>
                            <FileText size={14} />
                            <span>{doc}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Quick Actions */}
                    <div className="ci-actions">
                      {item.status === 'not-started' && (
                        <Button
                          variant="primary"
                          size="sm"
                          onClick={() => updateChecklistItemStatus(item.id, 'in-progress')}
                        >
                          Mark as In Progress
                        </Button>
                      )}
                      {item.status === 'in-progress' && (
                        <Button
                          variant="primary"
                          size="sm"
                          onClick={() => navigate('/upload-documents')}
                        >
                          Upload Documents <ArrowRight size={14} style={{ marginLeft: '4px' }} />
                        </Button>
                      )}
                      {item.status === 'approved' && (
                        <span className="ci-approved-tag">
                          <CheckCircle2 size={16} /> This approval has been granted
                        </span>
                      )}
                    </div>
                  </div>
                )}
              </Card>
            );
          })}
        </div>
      </div>
    </DashboardLayout>
  );
}
